### ISSUE TITLE
Automated tests for opening editor via LTI

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#122]
Similar to #109 (PR #114) we also want to test the opening of the Serlo editor via LTI

Functionality provided by lti.js will only be tested where it is important, like handling invalid token or unregistered platforms.  

## Tasks:

- [x] [Add cypress test: Editor is not opened in edit mode when postContentApiUrl is not present](https://github.com/serlo/ece-as-a-service/issues/131)
- [x] Add test: Editor can be opened successfully using LTI flow. (already done)
- [x] #177
  - Should be handled by lti.js like it is supposed to. But this is important.
- [x] [Add test: LTI launch fails with error message when id_token.iss sent by edu-sharing is not a registered platform URL.](https://github.com/serlo/ece-as-a-service/issues/175)
- [ ] Add test: LTI launch fails with error message when session cookie set by lti.js is not sent along with the launch request or invalid.
- [x] #189
- [ ] Add test: Editor shows error message, when request to get or save content failed.
  - What could cause this?: Edu-sharing session expired, user logged out on edu-sharing, permissions on edu-sharing changed, ...

**Comment by kulla** [comment]
Follow ups in #218 and #219
